### ISSUE TITLE
iteration 2 report

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#100]
follow bobby's guidelines: http://www.cs.sfu.ca/CourseCentral/276/bobbyc/a/RequirementsDocumentOverview.pdf

**Comment by BrendinGreen** [comment]
Google Doc: 
https://docs.google.com/document/d/16fZ8MkBW3zlw5uNjpMWKz7aNxX-hgjf7AU3gD3Rl0Qg/edit

**Comment by kevinzhangftw** [comment]
google says it is view only

**Comment by BrendinGreen** [comment]
Apologies, Updated.

**Comment by digitalSalt** [comment]
some stuff for reference here: #1
