### ISSUE TITLE
Map UI

### ISSUE THREAD

**Issue by BrendinGreen** [digitalSalt/GeoBox#105]
* dot for user symbol
* radius colour 
Refer to #61

**Comment by BrendinGreen** [comment]
Map Styles (Some options):
Night:
* https://snazzymaps.com/style/2/midnight-commander
* https://snazzymaps.com/style/13/neutral-blue
* https://snazzymaps.com/style/30/cobalt
Day:
* https://snazzymaps.com/style/83/muted-blue
* https://snazzymaps.com/style/27/shift-worker
* https://snazzymaps.com/style/18625/flat-design-map

**Comment by kevinzhangftw** [comment]
i am ok with maps unless anyone has strong opinions on maps styles. Icon update looks great. I think we can improve the UI overtime as we see fit

**Comment by kevinzhangftw** [comment]
some mapstyles were demo today, i liked the black and orange one for night, i think for day we want the orange one but not too orange
