### ISSUE TITLE
Dashboard button not appearing on initial load.

### ISSUE THREAD

**Issue by BrendinGreen** [digitalSalt/GeoBox#112]
Dashboard button does not appear unless the user logs in as admin, this means that even if I have a session as an admin, the dashboard button will not appear till a login is made. This may have to do with the flag for admin being set only on login @digitalSalt .

**Comment by digitalSalt** [comment]
proposed fix at d4b42f61a65727ae65c35c975400d2dca1a54c4c, feel free to merge it into pull req #110

**Comment by digitalSalt** [comment]
fixed on dev at d4b42f61a65727ae65c35c975400d2dca1a54c4c
