### ISSUE TITLE
Mapcontroller -> Books

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#117]
Upon userlocation updated,

DocumentService.fetchfiles()
BookService.fetchbooks()

When a user selects a book, 
book.fetchesContent()
will return all files within the book

**Comment by digitalSalt** [comment]
could potentially be done within document service

currently there is a service.docs array in doc service, we could ass a service.books array. 
depending on how we implement fetchBooks on the server side, we can either parse books and documents from the response from the existing POST call (preferred, i think). Or if necessary, we can make a separate POST for books, to a new action on the rails side

**Comment by digitalSalt** [comment]
done on branch Angelina as of 2eb68eb075b8e14a99ccd474d7b2f37eca9cf71e
