### ISSUE TITLE
Deploy to Geobox.xyz

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#120]
bye bye heroku

**Comment by digitalSalt** [comment]
we will try to get this custom domain name up on heroku. Somehow!

**Comment by digitalSalt** [comment]
in `document.service.js.erb` and `user.service.js.erb`, consider changing production base url to `https://geobox.xyz` from `https://geobox.herokuapp.com`

**Comment by kevinzhangftw** [comment]
ok. that seems like the issue. Unfortunately I had to update the master branch because heroku can only be pushed through master. we should discuss if we want to keep master this way
