### ISSUE TITLE
Books display on sidebar and map

### ISSUE THREAD

**Issue by digitalSalt** [digitalSalt/GeoBox#123]
Books have a different Icon on the map
Books have their own pane in the sidebar, which a book is clicked, the sidebar is updated with the files belonging to the book

**Comment by veriest** [comment]
Did this not happen yet? I swore we did this already...

**Comment by digitalSalt** [comment]
I believe Bredin has put a separate icon and tab for books on the sidebar but there's still work left to do

**Comment by BrendinGreen** [comment]
I am currently working on getting files to show up in the modal. I can also add the icons if no-one is working on that.

**Comment by digitalSalt** [comment]
done, everything in specs work!
