### ISSUE TITLE
Create a book, adding docs to the book

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#126]
User click to create a book
-client auto generate key

-add files to a book
-book with docs added

-anyone can see the book on map, but only users that knows pass phrase can see the docs in the book.

**Comment by kevinzhangftw** [comment]
for token generator
https://github.com/genericsteele/token_phrase

**Comment by BrendinGreen** [comment]
Chose not to go with generator. DONE.
