### ISSUE TITLE
behaviour of lat lang in files that belong to a book

### ISSUE THREAD

**Issue by digitalSalt** [digitalSalt/GeoBox#129]
what to do?
* files don't have lat lang if they belong to a book
   * files are wiped when book is wipted
* files have their own lat lang
   * when book is deleted, files are "sprayed" across the map to their own locations

**Comment by kevinzhangftw** [comment]
files have the same latlng that belong to the book. if the a book is deleted, all files are 'deleted'

**Comment by kevinzhangftw** [comment]
I would be ok with shallow delete

**Comment by BrendinGreen** [comment]
Went with full delete.
