### ISSUE TITLE
Investigate Mapcontroller Interval race condition

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#152]
how does interval time affects map displayed. $ctrl.autoUpdate = false; investigate

**Comment by digitalSalt** [comment]
proposed fix on 620015a729a51fdae569e57eafd0fd3fa3208b6c

@kevinctzhang maybe take a look and see if the bug still persists, it seems alright to me now.

**Comment by digitalSalt** [comment]
closing as fixed
