### ISSUE TITLE
red path remote exp

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#153]

**Comment by kevinzhangftw** [comment]
in sidebar controller, add if else conditionals if status != OK 
if (status == 'OK'){
+					let fly_lat = result[0].geometry.location.lat();
+					let fly_lng = result[0].geometry.location.lng();
+					$rootScope.$broadcast('ready_to:fly', {
+						fly_lat: fly_lat,
+						fly_lng: fly_lng
+					});
+					$ctrl.flewAway = true;
+				}

**Comment by digitalSalt** [comment]
basic feedback for users in the case of geocoding errors done on 6223e7676978a517a9eee5774285cd344bd056b2

this issue should be reopened if more elaborate error case behaviour is required
