### ISSUE TITLE
chatroom

### ISSUE THREAD

**Issue by digitalSalt** [digitalSalt/GeoBox#158]
Have a chatroom that has lat lng, similar to files and books
Chatrooms can be displayed on the map
chatrooms are discovered and enumerated on the sidebar similar to files and books 
chatrooms can be searched just like files and books

**Comment by kevinzhangftw** [comment]
I have looking into chatroom and i have some troubles with this gem
[](https://github.com/TsaiKoga/chatroom
)

Suppose an easy way to implement through sidebar, seems like we need to modify the user model to allow for this functionality? 

Add the chatroom to your view.

<%= render "chatroom/messages/chatroom" %>

Do we want to show which user sent a message? If so, it seems alittle more configuration.
#####Add User to the Message:

Add a migration and add your code to show user's name in message_helper.rb:

rails g migration add_user_id_to_messages
Add hidden field about user_id in chatroom/message_helper.rb so as create the message with its ower:

<%= f.hidden_field :user_id, :value => current_user.id %>
Allow params get the user_id in chatroom/messages_controller.rb:

	params.require(:message).permit(:content, :user_id)

Not sure how i would implement this part.

**Comment by digitalSalt** [comment]
Interesting. To do this it looks like we need to run a faye server https://faye.jcoglan.com/ ?

here is one of the alternative options: https://github.com/mikemarsian/conversejs-rails

a better basic understanding of the underlying backend tech (node faye server vs. XMPP server) is probably needed to make a good choice here.

**Comment by digitalSalt** [comment]
here's another alternative: https://github.com/systenics/ChatRoom

**Comment by digitalSalt** [comment]
starter code using the `chatroom` gem @kevinzhangftw  mentioned is at c28f2d420a33a5f2ab572c204ee7fa381f1a7ea5

run `bundle exec rackup private_pub.ru -s thin -E production` on a different terminal to start the faye server and get live chatroom updates
