### ISSUE TITLE
Detail Modal View

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#160]
Currently, when user click on document, it goes straight to download. 
Problem: while this is ok for demo, it causes 2 issues, user will have to download the file eveytime they view it, and secondly, going back home take a long time because the map takes a while to load.

Proposed solution: when user click on document, open a detail modal view that lets user preview the file before downloading it. that way, user can stay in the app without having to wait for the map to load again.

Ideas: A detail modal view should consist the name of the document, iframe showing the document, and possibly upvotes/downvotes or comments section below.

**Comment by digitalSalt** [comment]
PR open at #161, pending some possible refactoring

**Comment by kevinzhangftw** [comment]
done
