### ISSUE TITLE
Mutual Radius function for checking if two latlngs are near each other

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#19]
def mutualRadius?(userCurrentLatlng, file.latlng)
     setRadius = 500 #TODO we should decide what we want radius to be
     deltaLat = userCurrentLatlng.Lat - file.latlng.Lat
     deltaLng = userCurrentLatlng.Lng - file.latlng.Lng
     distanceInDeg = (deltaLat * deltaLat + deltaLng * deltaLng) ** 0.5 #pythag hypotenuse

     return (distanceInDeg < setRadius)
end
#sudo code 
for each file in DB:
     if mutualRadius?(userCurrentLatlng, file.latlng):
            return file key
     else
            do nothing

**Comment by BrendinGreen** [comment]
I've got the formula for this which takes into account the earths curvature. Its a little overkill though, especially since we are talking about distances where curvature is ~ 0.

**Comment by veriest** [comment]
In that case let’s just leave it as is to keep things simple.

**Comment by kevinzhangftw** [comment]
earth curvature to be considered later. MutalRadius? lives in documenthelper, issues closed
