### ISSUE TITLE
Guest login map not appearing

### ISSUE THREAD

**Issue by BrendinGreen** [digitalSalt/GeoBox#20]
Possibly a turbolinks issue.

**Comment by BrendinGreen** [comment]
Unfortunately, I don't think that the gems installed will work @veriest. It seems that jquery-turbolinks is deprecated and not compatible with turbolinks 5 and up. This page has some other options: https://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links

**Comment by veriest** [comment]
@BrendinGreen: you’re right, weird I didn’t notice that. It’ll have to be the other way then—I’ll take a look when I get back to my computer in a bit.
