### ISSUE TITLE
Implement login iteration 0 

### ISSUE THREAD

**Issue by digitalSalt** [digitalSalt/GeoBox#5]
Specs: 
* New user should be able to sign up
* New user should be able to bypass login by choosing to login as guest
* Create special admin users 
* Invalid username combination login should fail
* Redirect to application homepage after successful login or sign up
* Session management - when a user has logged in, remember the user session cookie and don't require login again in the same browser session unless user logs out
* Password are hashed.

**Comment by BrendinGreen** [comment]
@digitalSalt Do we want a "forgot password" option? Or should we leave that for a later iteration?

**Comment by digitalSalt** [comment]
@BrendinGreen  I think "forgot password" option should be either left to a later iteration or dealt with in a seperate issue for iteration 0, since it might include sending emails with a mail client.

**Comment by kevinzhangftw** [comment]
New user should be able to sign up- UI Test done
New user should be able to bypass login by choosing to login as guest -UI Test done
Create special admin users -Tobe implemented
Invalid username combination login should fail -UI Test done
Redirect to application homepage after successful login or sign up -UI Test done
Session management - when a user has logged in, remember the user session cookie and don't require login again in the same browser session unless user logs out -UI Test done
Password are hashed -UI Test done
