### ISSUE TITLE
Google cloud storage with carrierwave

### ISSUE THREAD

**Issue by veriest** [digitalSalt/GeoBox#56]

**Comment by digitalSalt** [comment]
have you guys checked this out? maybe worth taking a look at
https://github.com/metaware/carrierwave-google-storage

**Comment by BrendinGreen** [comment]
Yup, we know about all of these different options. We can compare between just using the gem and using carrierwave by itself.

**Comment by BrendinGreen** [comment]
Unfortunately, we can't use that gem as it is too old (compared to carrierwave). Setting up carrierwave for gCloud is easy.

**Comment by digitalSalt** [comment]
brendin done it. closing as surrogate of brendin, he satisfied
