### ISSUE TITLE
QA- User testing

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#60]
sign up download file
sign up upload file, download file
login download file
login upload file, download file
guest login down file only

-multiple user login user login at the same time

**Comment by digitalSalt** [comment]
@tudatn please comment on progress

**Comment by tudatn** [comment]
integration tests for upload still failed for both regular users and admins with error "latitude can't be blank". Not yet find the way to figure it out, it may be due to the browser doesn't allow to get location when we do in chrome_driver.

**Comment by tudatn** [comment]
I'd say tests for the 2nd iterations would have all unit tests we need. Integrations for login/ logout are good. Upload/ download we can just leave there as a pending issue.

**Comment by kevinzhangftw** [comment]
I think pending issue is fair, given that the app work as expected from user's point of view. I will move this section to the wiki page so we can refer to it later.
