### ISSUE TITLE
UX Critique

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#61]
After using the app as a normal user, please provide critique in the following areas

ease of use: how can we make the app simpler to use?
responsiveness: do u still think the app is easy to use on mobile?
onboarding: is login process redunant?

features: what features should we be having?
UI: what UI is redunant? what UI should we add/consider?

**Comment by BrendinGreen** [comment]
Things we could do:
* Add download links to popup
* ~Replace Hamburger menu icon with 'file' icon~
