### ISSUE TITLE
refactor document service getdoc and sendloc method

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#67]
In document.service.js.erb, sendloc POSTs browser_lat and lng, but in the response it actually calls getDocs()! So now the function does more than just sendLoc

Consider refactor:
-sendLoc
-getDocs

possible simple function rename might fix this issue

**Comment by digitalSalt** [comment]
@kevinctzhang , take a look at https://github.com/digitalSalt/GeoBox/pull/66, 
particularly this refactor commit 68e9131eecde0f8e45fc48cd0a4a24bd4e0d7322

and see if that's inline with what you wanted to do

**Comment by kevinzhangftw** [comment]
it is better but still problematic. The getdoc function fetchs all the documents but is only called upon the completion of sendlocation. So I feel the sendlocation function name is not descriptive enough. I dont have a better idea now so i will think about this more.

**Comment by kevinzhangftw** [comment]
nevermind i saw ur new code. issue resolved. well done! i am impressed
