### ISSUE TITLE
store api keys more secure

### ISSUE THREAD

**Issue by digitalSalt** [digitalSalt/GeoBox#76]
for maps - home.html.erb, google maps API key

for gcloud - initializers/carrierwave.rb

options: 
1) Store as env variables
2) Store in config file with secret keys

**Comment by kevinzhangftw** [comment]
after looking at docs, i think i would like this to be done using secrets.yml  i willl look up how to do this

**Comment by kevinzhangftw** [comment]
lol there is a gem for everything
gem 'heroku_secrets'

**Comment by kevinzhangftw** [comment]
[](https://stackoverflow.com/questions/21544626/how-do-you-manage-secret-keys-and-heroku-with-ruby-on-rails-4-1-0beta1/22458102#22458102)

**Comment by kevinzhangftw** [comment]
https://stackoverflow.com/questions/21544626/how-do-you-manage-secret-keys-and-heroku-with-ruby-on-rails-4-1-0beta1/22458102#22458102

**Comment by kevinzhangftw** [comment]
look for pull request and configure heroku
https://devcenter.heroku.com/articles/config-vars

**Comment by kevinzhangftw** [comment]
on staging
