### ISSUE TITLE
sessionStorage security issue

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#95]
regular user or even guest(!) can go to window.sessionStorage and create an admin field set to true, giving them view of the admin header bar!!
- actually visiting any admin pages will be blocked by the server tho. Still, not good that they can see

* possible fix: obfuscate field in session storage indicating admin.
* ajax calls

**Comment by digitalSalt** [comment]
done on branch john as of ece2eed26ffea695fb8544eb5815c42bd56025d7

**Comment by digitalSalt** [comment]
fixed on dev as of 00a79ed7a34b547487881a501130e6fffe5e8f11
