### ISSUE TITLE
Sidebar improvements (User panel, Settings panel(iteration 3))

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#98]
Clean up non wrapping description
Time information
 *  ~moment.js - look into~ done
* User profile information
  * ~user basic information(username, email)~
  * ~user active since time, last profile update time~
  * files uploaded by the user
     * ~file names~
     * option to delete, modify the files(?)
     * a search bar for files 
     * more?  
  
* rooms that the user created(?).

**Comment by digitalSalt** [comment]
I feel like from the POV of managing harassment, there's a point against letting users edit or delete files they've uploaded, in the event that they upload offensive material and then change/delete it so admins have no means of verifying

**Comment by kevinzhangftw** [comment]
i can find out conventions for handling this matter. However, if gcloud purges too often this issue can also occur

**Comment by kevinzhangftw** [comment]
we agreed for today to allow users download files but not edit. issue can be opened again or create new issue on letting users edit or delete files they've uploaded
